### ISSUE TITLE
Повторение кода

### ISSUE THREAD

**Issue by banyrule** [AishSI/labyrinth#7]
https://github.com/AishSI/labyrinth/blob/c9bb46f3597d9f0547fcde0daa7b773d927ace7b/DiagonalMazeTask.cs#L32

Тут лучше не выносить метод, а чуть проще:
```csharp
bool IsOnPoint(this Robot robot, int y, int x) { ... }
...
if (IsOnPoint(robot, height, width)) 
    return;

var direction = robot.Y < height
    ? Direction.Down;
    : Direction.Right

while (!IsOnPoint(robot, height, width)
     robot.MoveTo(direction );
```
А что будет, если робот перескочит финиш по обоим координатам?

**Comment by AishSI** [comment]
> А что будет, если робот перескочит финиш по обоим координатам?
Этого не может быть, т.к. логика решения была такова, что расчитывается количество полных ходов "конем", после которых робот либо попадает точно на финиш, либо не доскакивает до него пол-хода - по горизонтали или по вертикали. После чего делает последний рывок по той оси, по которой он не достиг финиша.
Но мне это тоже "не ндравиться", так что буду думать по твоим подсказкам.
